name: Node.js CI/CD Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Repo checkout karna
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Node.js setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Fix Jest permissions
        run: chmod +x node_modules/.bin/jest


      # Step 4: Run tests
      - name: Run tests
        run: npm test

      # Step 5: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 6: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-cicd:latest .

      # Step 7: Push Docker image to DockerHub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-cicd:latest

